apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-clone-app
  labels:
    app: nodejs-clone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-clone-app
  template:
    metadata:
      labels:
        app: nodejs-clone-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: nodejs-clone-app
        image: gunjankhanal/nodejs-clone:latest        
        ports:
        - containerPort: 3000
